{{- range .Values.middleware }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.middlewareNamespace }}
spec:
{{ .spec | toYaml | indent 2 }}
---
{{- end }}