{{- range .Values.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .endpoint }}
  ports:
  - name: {{ .port.name }}
    port: {{ .port.number }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: {{ .port.name }}
    port: {{ .port.number }}
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- range .entryPoints }}
  entryPoints:
  - {{ . }}
  {{- end }}
  routes:
  - match: Host(`{{ .url }}`)
    kind: Rule
    {{- range .middlewares }}
    middlewares:
    - name: {{ .name }}
      namespace: {{ $.Release.Namespace }}
    {{- end }}
    services:
    # WIP; hardcoded as Service right now
    - kind: Service
      name: {{ .name }}
      port: {{ .port.number }}
{{- end }}