name: guacamole-with-traefik
version: v1.0.0
appVersion: v1.5.5
description: Apache Guacamole Umbrella chart that houses the IngressRoute for Traefik.
home: https://github.com/solo-laboratories/devops-helm
sources:
- https://charts.beryju.io
dependencies:
- name: guacamole
  version: v1.4.1
  repository: https://charts.beryju.io
maintainers:
- name: Mark Brown
  email: markus@sololab.one
  url: https://github.com/markbrown87