deployment:
  kind: DaemonSet # Change to Deployment if you don't want to make certain traefik is on each node.
  revisionHistoryLimit: 3
  podAnnotations:
    prometheus.io/port: "8082"
    prometheus.io/scrape: "true"
providers:
  kubernetesIngress:
    publishedService:
      enabled: true

priorityClassName: "system-cluster-critical"
tolerations:
- key: "CriticalAddonsOnly"
  operator: "Exists"
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"
- key: "node-role.kubernetes.io/master"
  operator: "Exists"
  effect: "NoSchedule"
service:
  ipFamilyPolicy: "PreferDualStack"

globalArguments:
- --global.sendanonymoususage=false
- --global.checknewversion=true
additionalArguments:
- --serversTransport.insecureSkipVerify=true
ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
  # postgrest:
  #   port: 5432
  #   expose:
  #     default: true
