# Great reference for values: https://artifacthub.io/packages/helm/nextcloud/nextcloud?modal=values
nextcloud:
  host: nextcloud.example.com

  strategy:
    type: RollingUpdate

  extraEnv:
  - name: OVERWRITECLIURL
    value: https://nextcloud.example.com
  - name: OVERWRITEPROTOCOL
    value: https

persistence:
  enabled: true
  accessMode: ReadWriteMany
  size: 100Gi # Or Whatever size space you want Nextcloud to have

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-postgresql.nextcloud.svc.cluster.local:5432
  user: nextcloud
  password: nextcloud
  database: nextcloud

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        password: nextcloud
  primary:
    persistence:
      enabled: true