# Great reference for modifying values: https://artifacthub.io/packages/helm/bitnami/postgresql?modal=values
auth:
  username: user
  password: password 
  database: database 
persistence:
  size: 8Gi