# Great reference for modifying Application to your needs: https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argo-cd
spec:
  destination:
    name: ''
    namespace: coder
    server: 'https://kubernetes.default.svc'
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
  - repoURL: https://helm.coder.com/v2
    targetRevision: 2.14.2 # Change version here
    chart: coder
    helm:
      valueFiles:
      - $values/coder/db-values.yaml # Change where your values file is in remote repository. $values is at root.
  - repoURL: 'https://github.com/some-user/private-values-repo' # Change this to point to where your values file is restored.
    targetRevision: main
    ref: values 
  project: default