name: coder-with-traefik
version: v1.1.0
appVersion: v2.14.2
description: Coder v2 umbrella chart that houses an IngressRoute for clusters using Traefik
home: https://github.com/solo-laboratories/devops-helm
sources:
- https://github.com/coder/coder/tree/main/helm/coder
dependencies:
- name: coder
  version: 2.14.2
  repository: https://helm.coder.com/v2
- name: ingressroutes
  version: v1.0.0
  repository: https://solo-laboratories.github.io/helm-charts
maintainers:
- name: Mark Brown
  email: markus@sololab.one
  url: https://github.com/markbrown87