apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: <your-email-address-here>
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          # Notice cloudflare -- refer back to Cert Manager to figure out what to use for your provider
          cloudflare:
            email: <your-email-address-here>
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
           - "<your-domain-request-here>" # Subdomain works here as well
