apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: <some-api-token-here> # Details: https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/#api-tokens
